use_frameworks!

platform :ios, '9.0'

target 'AZLCache_Example' do
  pod 'AZLCache', :path => '../'

  target 'AZLCache_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
